export const VERIFICATION_SCHEMA = {
  name: "answer_verification",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      isRelevant: {
        type: "boolean",
        description:
          "Whether the trusted source excerpt is relevant to the question/answer topic.",
      },
      approve: {
        type: "boolean",
        description:
          "Whether the answer should be allowed for publishing (true can include WARN).",
      },
      category: {
        type: "string",
        enum: [
          "Accurate",
          "Contradicts Trusted Source",
          "Not Supported by Trusted Source",
          "Potentially Harmful Medical Advice",
          "Unclear",
          "Error",
          "Age Gap / Power Imbalance",
          "Potential Grooming Risk",
          "Risky Relationship Dynamics",
          "Authority Figure Involved",
          "Emotional Manipulation Risk",
          "Unequal Emotional Maturity",
          "Dependency Risk",
          "Boundary Concerns",
          "Pressure to Move Too Fast",
          "Isolation From Friends or Family",
          "Peer Pressure Risk",
          "Risky Social Situation",
          "Substance Pressure",
          "Party Safety Concern",
          "Loss of Control Risk",
          "Encouraging Risky Behavior",
          "Normalization of Harmful Behavior",
          "Consent Gray Area",
          "Ambiguous Consent Situation",
          "Pressure Around Sexual Activity",
          "Readiness Unclear",
          "Emotional Safety Concern",
          "Intimacy Pressure",
          "Lack of Informed Consent",
          "Unhealthy Body Image Messaging",
          "Diet Culture Risk",
          "Weight Fixation Concern",
          "Food Restriction Warning",
          "Appearance Pressure",
          "Comparison Pressure",
          "Self-Esteem Risk",
          "Emotional Vulnerability",
          "Distress Signals",
          "Lack of Support System",
          "Normalization of Emotional Pain",
          "Avoidance of Help-Seeking",
          "Unhealthy Coping Strategy",
          "Impulsive Decision Making",
          "Long-Term Consequences Unclear",
          "Lack of Adult Guidance",
          "Overconfidence Risk",
          "Life Experience Gap",
          "Potential Harm – Context Dependent",
          "Situational Risk",
          "Requires Careful Consideration",
          "Sensitive Topic – Caution Advised",
          "Complex Situation",
        ],
      },
      reason: { type: ["string", "null"] },
      suggestedFix: {
        type: ["string", "null"],
        description:
          "Optional: a safer rewrite. Keep it short and teen-appropriate.",
      },
      confidence: { type: "number", minimum: 0, maximum: 1 },
    },
    required: [
      "isRelevant",
      "approve",
      "category",
      "reason",
      "suggestedFix",
      "confidence",
    ],
  },
};
